package com.pbess.qrphotostudioultra.seizuredetector.wear

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Service
import android.content.Context
import android.content.Intent
import android.hardware.Sensor
import android.hardware.SensorEvent
import android.hardware.SensorEventListener
import android.hardware.SensorManager
import android.os.*
import android.util.Log
import com.pbess.qrphotostudioultra.seizuredetector.wear.R
import androidx.core.app.NotificationCompat
import androidx.core.content.ContextCompat
import com.google.android.gms.tasks.Tasks
import com.google.android.gms.wearable.PutDataMapRequest
import com.google.android.gms.wearable.Wearable
import kotlinx.coroutines.*
import java.util.UUID
import kotlin.math.sqrt

/**
 * Foreground service that monitors all available sensors on the watch,
 * runs the detection algorithm, and triggers phone alerts via Data Layer.
 *
 * Wake lock is bounded to [WAKE_LOCK_TIMEOUT_MS] to prevent indefinite CPU hold.
 * The service re-acquires on [onStartCommand] if still monitoring.
 */
class SensorMonitoringService : Service(), SensorEventListener {

    // ── Sensors ────────────────────────────────────────────────────────────

    private lateinit var sensorManager: SensorManager
    private var accelSensor: Sensor? = null
    private var gyroSensor: Sensor? = null
    private var heartSensor: Sensor? = null
    private var pressureSensor: Sensor? = null
    private var magSensor: Sensor? = null

    // ── Live sensor values (read by WearMainActivity via binder) ───────────

    @Volatile var magnitude = 0f; private set
    @Volatile var gyroMagnitude = 0f; private set
    @Volatile var heartRate = 0f; private set
    @Volatile var pressure = 0f; private set
    @Volatile var magnetometerMagnitude = 0f; private set
    private var lastPressure = 0f

    // ── Alert state ────────────────────────────────────────────────────────

    @Volatile var isMonitoring = false; private set
    @Volatile var isAlertPending = false; private set
    private var vibrationJob: Job? = null

    // Last eventId generated by this service; read by WearMainActivity for cancel.
    var lastEventId: String? = null
        private set

    // ── Runtime ────────────────────────────────────────────────────────────

    private val serviceScope = CoroutineScope(Dispatchers.IO + SupervisorJob())
    private var syncJob: Job? = null
    private var wakeLock: PowerManager.WakeLock? = null
    private var vibrator: Vibrator? = null

    // ── Binder ─────────────────────────────────────────────────────────────

    inner class LocalBinder : Binder() {
        fun getService(): SensorMonitoringService = this@SensorMonitoringService
    }

    private val binder = LocalBinder()
    override fun onBind(intent: Intent?): IBinder = binder

    // ── Lifecycle ──────────────────────────────────────────────────────────

    override fun onCreate() {
        super.onCreate()
        Log.d(TAG, "onCreate")
        sensorManager = getSystemService(SENSOR_SERVICE) as SensorManager
        vibrator = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            (getSystemService(VIBRATOR_MANAGER_SERVICE) as VibratorManager).defaultVibrator
        } else {
            @Suppress("DEPRECATION")
            getSystemService(VIBRATOR_SERVICE) as Vibrator
        }
        setupSensors()
        createNotificationChannel()
        ensureForeground()
        acquireWakeLock()
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        Log.d(TAG, "onStartCommand action=${intent?.action}")
        if (intent?.action == ACTION_STOP) {
            updateState(monitoring = false, alertPending = false)
            return START_NOT_STICKY
        }
        isMonitoring = true
        persistMonitoringState(true)
        registerListeners()
        startSyncing()
        ensureForeground()
        // Re-acquire wake lock if the previous one timed out naturally
        if (wakeLock?.isHeld == false) acquireWakeLock()
        return START_STICKY
    }

    override fun onTaskRemoved(rootIntent: Intent?) {
        ensureForeground()
        super.onTaskRemoved(rootIntent)
    }

    override fun onDestroy() {
        Log.d(TAG, "onDestroy")
        stopVibrating()
        unregisterListeners()
        syncJob?.cancel()
        serviceScope.cancel()
        releaseWakeLock()
        persistMonitoringState(false)
        super.onDestroy()
    }

    // ── Setup ──────────────────────────────────────────────────────────────

    private fun setupSensors() {
        accelSensor = sensorManager.getDefaultSensor(Sensor.TYPE_LINEAR_ACCELERATION)
            ?: sensorManager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER)
        gyroSensor = sensorManager.getDefaultSensor(Sensor.TYPE_GYROSCOPE)
        heartSensor = sensorManager.getDefaultSensor(Sensor.TYPE_HEART_RATE)
        pressureSensor = sensorManager.getDefaultSensor(Sensor.TYPE_PRESSURE)
        magSensor = sensorManager.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD)
    }

    private fun registerListeners() {
        try {
            accelSensor?.let {
                if (!sensorManager.registerListener(this, it, SensorManager.SENSOR_DELAY_NORMAL))
                    Log.e(TAG, "Failed to register accelerometer")
            }
            gyroSensor?.let {
                if (!sensorManager.registerListener(this, it, SensorManager.SENSOR_DELAY_NORMAL))
                    Log.e(TAG, "Failed to register gyroscope")
            }
            if (ContextCompat.checkSelfPermission(
                    this, android.Manifest.permission.BODY_SENSORS
                ) == android.content.pm.PackageManager.PERMISSION_GRANTED
            ) {
                heartSensor?.let {
                    if (!sensorManager.registerListener(this, it, SensorManager.SENSOR_DELAY_NORMAL))
                        Log.e(TAG, "Failed to register heart rate")
                }
            }
            pressureSensor?.let {
                if (!sensorManager.registerListener(this, it, SensorManager.SENSOR_DELAY_NORMAL))
                    Log.e(TAG, "Failed to register pressure")
            }
            magSensor?.let {
                if (!sensorManager.registerListener(this, it, SensorManager.SENSOR_DELAY_UI))
                    Log.e(TAG, "Failed to register magnetometer")
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error registering sensor listeners", e)
        }
    }

    private fun unregisterListeners() {
        sensorManager.unregisterListener(this)
    }

    // ── Sensor events ──────────────────────────────────────────────────────

    override fun onSensorChanged(event: SensorEvent) {
        when (event.sensor.type) {
            Sensor.TYPE_LINEAR_ACCELERATION, Sensor.TYPE_ACCELEROMETER -> {
                val x = event.values[0]; val y = event.values[1]; val z = event.values[2]
                val raw = sqrt(x * x + y * y + z * z)
                magnitude = if (event.sensor.type == Sensor.TYPE_ACCELEROMETER)
                    (raw - SensorManager.GRAVITY_EARTH).coerceAtLeast(0f)
                else raw
                detectSeizure()
            }
            Sensor.TYPE_GYROSCOPE -> {
                gyroMagnitude = sqrt(
                    event.values[0] * event.values[0] +
                    event.values[1] * event.values[1] +
                    event.values[2] * event.values[2]
                )
            }
            Sensor.TYPE_HEART_RATE -> {
                if (event.values.isNotEmpty()) heartRate = event.values[0]
            }
            Sensor.TYPE_PRESSURE -> {
                if (event.values.isNotEmpty()) {
                    lastPressure = pressure
                    pressure = event.values[0]
                }
            }
            Sensor.TYPE_MAGNETIC_FIELD -> {
                magnetometerMagnitude = sqrt(
                    event.values[0] * event.values[0] +
                    event.values[1] * event.values[1] +
                    event.values[2] * event.values[2]
                )
            }
        }
    }

    override fun onAccuracyChanged(sensor: Sensor?, accuracy: Int) {}

    // ── Detection ──────────────────────────────────────────────────────────

    private var lastHighTime = 0L
    private var lastMovementTime = 0L
    private var lastAlertTriggerTime = 0L

    private fun detectSeizure() {
        val now = System.currentTimeMillis()
        if (isAlertPending || (now - lastAlertTriggerTime < ALERT_COOLDOWN_MS)) return

        var score = magnitude + (gyroMagnitude * 2f)
        if (heartRate > 100f) score *= 1.2f
        // Note: pressure multiplier removed — too sensitive to elevation changes.
        // See Audit.md §D for rationale.

        if (score > DETECTION_THRESHOLD) {
            lastMovementTime = now
            if (lastHighTime == 0L) lastHighTime = now
            val durationMs = now - lastHighTime

            if (durationMs > DETECTION_DURATION_MS) {
                lastAlertTriggerTime = now
                triggerAlertOnPhone()
            }
        } else {
            // 500ms gap resets the window — increased from 150ms to survive OS scheduling jitter
            if (now - lastMovementTime > 500L) {
                lastHighTime = 0L
            }
        }
    }

    private fun triggerAlertOnPhone() {
        val eventId = UUID.randomUUID().toString()
        lastEventId = eventId
        Log.d(TAG, "Triggering alert: eventId=$eventId")

        // Wake screen briefly so user sees the alert
        acquireScreenWakeLock()

        // Bring watch UI to foreground
        val intent = Intent(this, WearMainActivity::class.java).apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_REORDER_TO_FRONT)
        }
        startActivity(intent)

        serviceScope.launch {
            try {
                val messageClient = Wearable.getMessageClient(this@SensorMonitoringService)
                val nodes = Tasks.await(
                    Wearable.getNodeClient(this@SensorMonitoringService).connectedNodes
                )
                nodes.forEach { node ->
                    messageClient.sendMessage(
                        node.id,
                        "/trigger_alert",
                        eventId.toByteArray(Charsets.UTF_8)
                    )
                }
                Log.d(TAG, "Sent /trigger_alert to ${nodes.size} node(s)")
            } catch (e: Exception) {
                Log.e(TAG, "Failed to send /trigger_alert", e)
            }
        }
    }

    // ── Sensor data sync to phone ──────────────────────────────────────────

    private fun startSyncing() {
        syncJob?.cancel()
        syncJob = serviceScope.launch {
            val dataClient = Wearable.getDataClient(this@SensorMonitoringService)
            while (isActive) {
                val req = PutDataMapRequest.create("/wear_sensor_data").apply {
                    dataMap.putFloat("magnitude", magnitude)
                    dataMap.putFloat("gyroMagnitude", gyroMagnitude)
                    dataMap.putFloat("heartRate", heartRate)
                    dataMap.putFloat("pressure", pressure)
                    dataMap.putFloat("magnetometerMagnitude", magnetometerMagnitude)
                    dataMap.putLong("timestamp", System.currentTimeMillis())
                }
                try {
                    Tasks.await(dataClient.putDataItem(req.asPutDataRequest().setUrgent()))
                } catch (e: Exception) {
                    Log.e(TAG, "Sync failed", e)
                }
                delay(2_000L)
            }
        }
    }

    // ── State management ───────────────────────────────────────────────────

    fun updateState(monitoring: Boolean, alertPending: Boolean) {
        val alertChanged = isAlertPending != alertPending
        isAlertPending = alertPending
        if (alertChanged) {
            if (isAlertPending) startVibrating() else stopVibrating()
        }
        if (!monitoring) {
            isMonitoring = false
            syncJob?.cancel()
            unregisterListeners()
            ensureForeground()
            stopSelf()
        } else {
            isMonitoring = true
            ensureForeground()
        }
    }

    // ── Vibration ──────────────────────────────────────────────────────────

    private fun startVibrating() {
        vibrationJob?.cancel()
        vibrationJob = serviceScope.launch {
            while (isActive && isAlertPending) {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    vibrator?.vibrate(
                        VibrationEffect.createOneShot(500, VibrationEffect.DEFAULT_AMPLITUDE)
                    )
                } else {
                    @Suppress("DEPRECATION")
                    vibrator?.vibrate(500)
                }
                delay(1_000L)
            }
        }
    }

    private fun stopVibrating() {
        vibrationJob?.cancel()
        vibrationJob = null
        vibrator?.cancel()
    }

    // ── Wake lock ──────────────────────────────────────────────────────────

    private fun acquireWakeLock() {
        val pm = getSystemService(Context.POWER_SERVICE) as PowerManager
        wakeLock = pm.newWakeLock(
            PowerManager.PARTIAL_WAKE_LOCK,
            "SeizureDetector:SensorWakeLock"
        )
        // Bounded to 4 hours. Service re-acquires on next onStartCommand if still needed.
        wakeLock?.acquire(WAKE_LOCK_TIMEOUT_MS)
        Log.d(TAG, "Wake lock acquired (${WAKE_LOCK_TIMEOUT_MS / 1000 / 60} min)")
    }

    private fun releaseWakeLock() {
        if (wakeLock?.isHeld == true) {
            wakeLock?.release()
            Log.d(TAG, "Wake lock released")
        }
        wakeLock = null
    }

    private fun acquireScreenWakeLock() {
        val pm = getSystemService(Context.POWER_SERVICE) as PowerManager
        @Suppress("DEPRECATION")
        pm.newWakeLock(
            PowerManager.SCREEN_BRIGHT_WAKE_LOCK or
            PowerManager.ACQUIRE_CAUSES_WAKEUP or
            PowerManager.ON_AFTER_RELEASE,
            "SeizureDetector:AlertWakeLock"
        ).acquire(10_000L)
    }

    // ── Persistent state ───────────────────────────────────────────────────

    private fun persistMonitoringState(active: Boolean) {
        val ctx = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N)
            applicationContext.createDeviceProtectedStorageContext()
        else applicationContext
        ctx.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            .edit().putBoolean(PREF_IS_MONITORING, active).apply()
    }

    // ── Foreground notification ────────────────────────────────────────────

    private fun createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                CHANNEL_ID,
                getString(R.string.notification_channel_name),
                NotificationManager.IMPORTANCE_HIGH
            ).apply {
                description = getString(R.string.notification_channel_description)
                enableLights(true)
                lockscreenVisibility = Notification.VISIBILITY_PUBLIC
                enableVibration(false)
            }
            getSystemService(NotificationManager::class.java)?.createNotificationChannel(channel)
        }
    }

    private fun ensureForeground() {
        val content = when {
            isAlertPending -> "ALERT TRIGGERED"
            isMonitoring -> getString(R.string.notification_content_monitoring)
            else -> "Seizure Detector Ready"
        }
        val intent = Intent(this, WearMainActivity::class.java)
        val pi = PendingIntent.getActivity(this, 0, intent, PendingIntent.FLAG_IMMUTABLE)

        val notification = NotificationCompat.Builder(this, CHANNEL_ID)
            .setContentTitle(getString(R.string.notification_title))
            .setContentText(content)
            .setSmallIcon(R.mipmap.ic_launcher)
            .setContentIntent(pi)
            .setOngoing(true)
            .setPriority(NotificationCompat.PRIORITY_MAX)
            .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
            .setCategory(NotificationCompat.CATEGORY_SERVICE)
            .setForegroundServiceBehavior(NotificationCompat.FOREGROUND_SERVICE_IMMEDIATE)
            .apply { if (isAlertPending) setFullScreenIntent(pi, true) }
            .build()

        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                startForeground(
                    NOTIFICATION_ID, notification,
                    android.content.pm.ServiceInfo.FOREGROUND_SERVICE_TYPE_HEALTH or
                    android.content.pm.ServiceInfo.FOREGROUND_SERVICE_TYPE_CONNECTED_DEVICE
                )
            } else {
                startForeground(NOTIFICATION_ID, notification)
            }
        } catch (e: Exception) {
            Log.e(TAG, "startForeground failed", e)
        }
    }

    // ── Constants ──────────────────────────────────────────────────────────

    companion object {
        private const val TAG = "SensorMonitoringService"
        private const val NOTIFICATION_ID = 1
        private const val CHANNEL_ID = "seizure_detection_channel"

        // Detection thresholds — heuristic, not clinically validated. See Audit.md §D.
        private const val DETECTION_THRESHOLD = 15f
        private const val DETECTION_DURATION_MS = 2_000L
        private const val ALERT_COOLDOWN_MS = 30_000L

        // 4-hour bounded wake lock. Service re-acquires if restarted.
        private const val WAKE_LOCK_TIMEOUT_MS = 4L * 60L * 60L * 1_000L

        const val PREFS_NAME = "monitoring_prefs"
        const val PREF_IS_MONITORING = "isMonitoring"
        const val ACTION_STOP = "com.pbess.seizuredetector.STOP_SENSOR_SERVICE"

        fun start(context: Context) {
            val intent = Intent(context, SensorMonitoringService::class.java)
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                context.startForegroundService(intent)
            } else {
                context.startService(intent)
            }
        }

        fun stop(context: Context) {
            val intent = Intent(context, SensorMonitoringService::class.java).apply {
                action = ACTION_STOP
            }
            context.startService(intent)
        }
    }
}
